import SwiftUI

public struct AxisLabels<Content: View>: View {
    @Environment(\.chartAxisConfig) private var axisConfig

    @State private var preferredDataPoints: [(Double, Double)] = []
    @State private var preferredXRange: ClosedRange<Double>?
    @State private var preferredYRange: ClosedRange<Double>?
    @State private var preferredXDomainMode: ChartXDomainMode = .numeric

    private let yAxisWidth: CGFloat = 42
    private let xAxisHeight: CGFloat = 24

    let content: () -> Content

    public init(@ViewBuilder content: @escaping () -> Content) {
        self.content = content
    }

    private var visibleXValues: [Double] {
        preferredDataPoints
            .filter { preferredXRange?.contains($0.0) ?? true }
            .map(\.0)
    }

    private var visibleYValues: [Double] {
        preferredDataPoints
            .filter { preferredXRange?.contains($0.0) ?? true }
            .map(\.1)
    }

    private var xRangeForScale: ClosedRange<Double>? {
        preferredXRange ?? axisConfig.axisXRange
    }

    private var xDomainModeForScale: ChartXDomainMode {
        preferredDataPoints.isEmpty ? axisConfig.axisXDomainMode : preferredXDomainMode
    }

    private var resolvedXAxisLabels: [ChartXAxisLabel] {
        if !axisConfig.axisXLabels.isEmpty {
            return axisConfig.axisXLabels
        }

        guard let autoCount = axisConfig.axisXAutoTickCount else { return [] }
        return autoGeneratedXAxisLabels(count: autoCount)
    }

    private var resolvedYAxisLabels: [String] {
        if !axisConfig.axisYLabels.isEmpty {
            return axisConfig.axisYLabels
        }

        guard let autoCount = axisConfig.axisYAutoTickCount else { return [] }
        return autoGeneratedYAxisLabels(count: autoCount)
    }

    private var hasYLabels: Bool {
        !resolvedYAxisLabels.isEmpty
    }

    private var hasXLabels: Bool {
        !resolvedXAxisLabels.isEmpty
    }

    private var effectiveYAxisWidth: CGFloat {
        hasYLabels ? yAxisWidth : 0
    }

    private var effectiveXAxisHeight: CGFloat {
        hasXLabels ? xAxisHeight : 0
    }

    private var leftAxisGutter: CGFloat {
        axisConfig.axisLabelsYPosition == .leading ? effectiveYAxisWidth : 0
    }

    private var rightAxisGutter: CGFloat {
        axisConfig.axisLabelsYPosition == .trailing ? effectiveYAxisWidth : 0
    }

    private var xScale: ChartXScale {
        let scaleValues = visibleXValues.isEmpty ? resolvedXAxisLabels.map(\.value) : visibleXValues
        return ChartXScale(values: scaleValues,
                           rangeX: xRangeForScale,
                           mode: xDomainModeForScale,
                           slotCountHint: max(scaleValues.count, resolvedXAxisLabels.count))
    }

    var yAxis: some View {
        VStack(spacing: 0) {
            ForEach(Array(resolvedYAxisLabels.reversed().enumerated()), id: \.offset) { index, axisYData in
                Text(axisYData)
                    .font(axisConfig.axisFont)
                    .foregroundColor(axisConfig.axisFontColor)
                    .frame(maxWidth: .infinity,
                           alignment: axisConfig.axisLabelsYPosition == .leading ? .trailing : .leading)

                if index < resolvedYAxisLabels.count - 1 {
                    Spacer(minLength: 0)
                }
            }
        }
        .padding(.horizontal, 4)
    }

    var xAxis: some View {
        GeometryReader { geometry in
            let safeSize = geometry.size.sanitized
            let width = safeSize.width
            let labels = visibleXAxisLabels(width: width)

            ZStack(alignment: .topLeading) {
                ForEach(Array(labels.enumerated()), id: \.offset) { _, xLabel in
                    positionedXLabel(xLabel, width: width)
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .frame(height: xAxisHeight, alignment: .top)
    }

    public var body: some View {
        GeometryReader { geometry in
            let safeSize = geometry.size.sanitized
            let axisHeight = effectiveXAxisHeight
            let chartHeight = max(0, safeSize.height - axisHeight)

            VStack(spacing: 0) {
                HStack(spacing: 0) {
                    if leftAxisGutter > 0 {
                        yAxis
                            .frame(width: leftAxisGutter, height: chartHeight, alignment: .trailing)
                    }

                    content()
                        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)

                    if rightAxisGutter > 0 {
                        yAxis
                            .frame(width: rightAxisGutter, height: chartHeight, alignment: .leading)
                    }
                }
                .frame(height: chartHeight, alignment: .top)

                if axisHeight > 0 {
                    HStack(spacing: 0) {
                        if leftAxisGutter > 0 {
                            Color.clear.frame(width: leftAxisGutter, height: axisHeight)
                        }

                        xAxis
                            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)

                        if rightAxisGutter > 0 {
                            Color.clear.frame(width: rightAxisGutter, height: axisHeight)
                        }
                    }
                    .frame(height: axisHeight, alignment: .top)
                }
            }
            .frame(width: safeSize.width, height: safeSize.height, alignment: .topLeading)
        }
        .onPreferenceChange(ChartDataPointsPreferenceKey.self) { snapshot in
            preferredDataPoints = snapshot.points
        }
        .onPreferenceChange(ChartXRangePreferenceKey.self) { range in
            preferredXRange = range
        }
        .onPreferenceChange(ChartYRangePreferenceKey.self) { range in
            preferredYRange = range
        }
        .onPreferenceChange(ChartXDomainModePreferenceKey.self) { mode in
            preferredXDomainMode = mode
        }
    }

    private func visibleXAxisLabels(width: CGFloat) -> [ChartXAxisLabel] {
        let labels = resolvedXAxisLabels.sorted(by: { $0.value < $1.value })
        guard labels.count > 2, width > 0 else { return labels }

        let rotationFactor = abs(axisConfig.axisXLabelRotation.degrees) > 0 ? 1.4 : 1.0
        let minimumSpacing = 28.0 * rotationFactor
        let minNormalizedDistance = minimumSpacing / width
        var filtered: [ChartXAxisLabel] = []
        var lastPlacedX = -Double.greatestFiniteMagnitude

        for (index, label) in labels.enumerated() {
            let x = xScale.normalizedX(for: label.value)
            if index == 0 || index == labels.count - 1 || (x - lastPlacedX) >= minNormalizedDistance {
                filtered.append(label)
                lastPlacedX = x
            }
        }

        return filtered
    }

    @ViewBuilder
    private func positionedXLabel(_ xLabel: ChartXAxisLabel, width: CGFloat) -> some View {
        let normalized = xScale.normalizedX(for: xLabel.value)
        let clamped = min(1.0, max(0.0, normalized))
        let label = axisLabelText(xLabel.title)

        if clamped <= 0.001 {
            label
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .leading)
        } else if clamped >= 0.999 {
            label
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .trailing)
        } else {
            label
                .position(x: width * CGFloat(clamped), y: xAxisHeight / 2)
        }
    }

    private func axisLabelText(_ title: String) -> some View {
        Text(title)
            .lineLimit(1)
            .minimumScaleFactor(0.8)
            .font(axisConfig.axisFont)
            .foregroundColor(axisConfig.axisFontColor)
            .rotationEffect(axisConfig.axisXLabelRotation, anchor: .top)
    }

    private func autoGeneratedXAxisLabels(count: Int) -> [ChartXAxisLabel] {
        guard count > 1 else { return [] }

        switch xDomainModeForScale {
        case .categorical:
            let values: [Double]
            if let range = xRangeForScale {
                let lower = Int(floor(range.lowerBound))
                let upper = Int(ceil(range.upperBound))
                values = Array(lower...upper).map(Double.init)
            } else {
                values = Array(Set(visibleXValues)).sorted()
            }

            guard !values.isEmpty else { return [] }
            return sampled(values, targetCount: count).map {
                ChartXAxisLabel(value: $0, title: formatAxisTick($0, format: axisConfig.axisXTickFormat))
            }

        case .numeric:
            let bounds: ClosedRange<Double>?
            if let range = xRangeForScale {
                bounds = range
            } else if let minValue = visibleXValues.min(), let maxValue = visibleXValues.max(), minValue != maxValue {
                bounds = minValue...maxValue
            } else {
                bounds = nil
            }

            guard let range = bounds else { return [] }
            let span = range.upperBound - range.lowerBound
            guard span.isFinite, span > 0 else { return [] }
            let step = span / Double(count - 1)
            return (0..<count).map { index in
                let value = range.lowerBound + step * Double(index)
                return ChartXAxisLabel(value: value, title: formatAxisTick(value, format: axisConfig.axisXTickFormat))
            }
        }
    }

    private func autoGeneratedYAxisLabels(count: Int) -> [String] {
        guard count > 1 else { return [] }

        let bounds: ClosedRange<Double>?
        if let preferredYRange = preferredYRange {
            bounds = preferredYRange
        } else if let minValue = visibleYValues.min(), let maxValue = visibleYValues.max(), minValue != maxValue {
            bounds = minValue...maxValue
        } else {
            bounds = nil
        }

        guard let range = bounds else { return [] }
        let span = range.upperBound - range.lowerBound
        guard span.isFinite, span > 0 else { return [] }
        let step = span / Double(count - 1)
        return (0..<count).map { index in
            let value = range.lowerBound + step * Double(index)
            return formatAxisTick(value, format: axisConfig.axisYTickFormat)
        }
    }

    private func sampled(_ values: [Double], targetCount: Int) -> [Double] {
        guard values.count > targetCount, targetCount > 1 else { return values }

        let stride = Double(values.count - 1) / Double(targetCount - 1)
        var result: [Double] = []
        for index in 0..<targetCount {
            let sampleIndex = Int(round(Double(index) * stride))
            let clampedIndex = max(0, min(values.count - 1, sampleIndex))
            result.append(values[clampedIndex])
        }
        return Array(Set(result)).sorted()
    }

    private func formatAxisTick(_ value: Double, format: ChartAxisTickFormat) -> String {
        switch format {
        case .number:
            if abs(value.rounded() - value) < 0.001 {
                return String(Int(value.rounded()))
            }
            return String(format: "%.1f", value)
        case .shortDate:
            let formatter = DateFormatter()
            formatter.dateStyle = .short
            formatter.timeStyle = .none
            return formatter.string(from: Date(timeIntervalSince1970: value))
        }
    }
}
